web:
  build: .
  command: bash -c "rm -f /usr/src/app/tmp/pids/server.pid && rails s -p 3000 -b '0.0.0.0'"
  environment:
    - WEB_CONCURRENCY=1
    - MAX_THREADS=1
    - DATABASE_URL=postgres://postgres:postgres@db:5432
  volumes:
    - .:/usr/src/app
  ports:
    - "3000:3000"
  expose:
    - "3000"
  links:
    - db

db_data:
  image: postgres:9.4.5
  entrypoint: /bin/bash

db:
  image: postgres:9.4.5
  volumes_from:
    - db_data
  environment:
    POSTGRES_PASSWORD: postgres
    POSTGRES_USER: postgres
  ports:
    - "5432:5432"
  expose:
    - "5432"
